---
output: github_document
bibliography: workshoprefs.bib
---

# Working with origin-destination and activity data to model decarbonisation

In this session we will explore the potential for origin-destination data to be used as a basis for decarbonisation research and informing local policies.

The workshop takes place in the context of the 2018 report [All Change from the Commission on Travel Demand](http://www.demand.ac.uk/wp-content/uploads/2018/04/FutureTravel_report_final.pdf), and subsequent research and policy documents emphasising the importance of demand reduction [@brand2020].
The second recommendation of the report is that:

> Travel demand futuring tools should be open source

In 2021 the software is now available for this to happen, with tools such as the Propensity to Cycle Tool and the Place Based Carbon Calculator being used by decision makers at every level in government and civil society concerned with transport sustainability.
There is now a diverse and rapidly growing ecosystem of open source software for geographic analysis in transport planning [@lovelace2021].

The power of origin-destination data in this context is [well-known](https://github.com/creds2/od-data), as widely available input datasets that can be used for modelling scenarios of change.
In this workshop we will discuss how such origin destination datasets can be used and how we can go beyond simple OD data analysis based on a single trip type such as that presented in the Propensity to Cycle Tool to provide a strong foundation for transport data research.
The workshop will include practical and policy-relevant questions and will coincide with the release of a newly available subset of activity model data from Sao Paulo.
There is no strict agenda but the workshop will include the following components:

-   Live demo with R

-   Live demo with A/B Street

-   Presentation of a new example dataset

-   How can we visualise the data with static maps?

-   How can we visualise the data with animated static maps (e.g. with gganimate)

-   How can we visualise the data with animated interactive maps (e.g. with mapdeck)

-   How can we model destination switching and working from home?

-   How can origin-destination data be used to support decarbonisation research and policy?

## References
